[package]
name = "hellcat"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.0.1"
dirs = "5.0.0"
libaes = "0.7.0"