[package]
name = "hellcat"
version = "0.1.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { features = ["full"] }
dirs = "5.0.0"
libaes = "0.7.0"